export const GET_BETS_REQUEST = 'GET_BETS_REQUEST';
export const GET_BETS_SUCCESS = 'GET_BETS_SUCCESS';

export const GET_ELIGIBLE_EVENTS_REQUEST = 'GET_ELIGIBLE_EVENTS_REQUEST';
export const GET_ELIGIBLE_EVENTS_SUCCESS = 'GET_ELIGIBLE_EVENTS_SUCCESS';

export const ADD_BET_REQUEST = 'ADD_BET_REQUEST';
export const ADD_BET_SUCCESS = 'ADD_BET_SUCCESS';

export const ADD_PENDING_BET_REQUEST = 'ADD_PENDING_BET_REQUEST';
export const ADD_PENDING_BET = 'ADD_PENDING_BET';

export const VERIFY_BET = 'VERIFY_BET';

export const ADD_EVENT_REQUEST = 'ADD_EVENT_REQUEST';
export const ADD_EVENT_SUCCESS = 'ADD_EVENT_SUCCESS';

export const ADD_PENDING_EVENT_REQUEST = 'ADD_PENDING_EVENT_REQUEST';
export const ADD_PENDING_EVENT = 'ADD_PENDING_EVENT';

export const VERIFY_EVENT = 'VERIFY_EVENT';
