export const GET_BETS_REQUEST = 'GET_BETS_REQUEST';
export const GET_BETS_SUCCESS = 'GET_BETS_SUCCESS';

export const GET_ELIGIBLE_EVENTS_REQUEST = 'GET_ELIGIBLE_EVENTS_REQUEST';
export const GET_ELIGIBLE_EVENTS_SUCCESS = 'GET_ELIGIBLE_EVENTS_SUCCESS';
