export const GET_BETS_REQUEST = 'GET_BETS_REQUEST';
export const GET_BETS_SUCCESS = 'GET_BETS_SUCCESS';

export const ADD_BET_REQUEST = 'ADD_BET_REQUEST';

export const GET_ELIGIBLE_EVENTS_REQUEST = 'GET_ELIGIBLE_EVENTS_REQUEST';
export const GET_ELIGIBLE_EVENTS_SUCCESS = 'GET_ELIGIBLE_EVENTS_SUCCESS';

export const ADD_PENDING_BET_REQUEST = 'ADD_PENDING_BET_REQUEST';
export const ADD_BET_SUCCESS = 'ADD_BET_SUCCESS';

export const ADD_PENDING_BET = 'ADD_PENDING_BET';

export const ADD_VERIFIED_BET = 'ADD_VERIFIED_BET';

export const VERIFY_BET = 'VERIFY_BET';
